version: '3.0'
services:
  app: &app
    build: &app-build
      context: .
      dockerfile: Dockerfile.development
      args:
        RUBY_VERSION: 2.4.2
    environment:
      LANGUAGE_SERVER_RUBY_REMOTE_ROOT: $PWD
    volumes:
      - vendor:/vendor
      - home:/home/ruby
    depends_on:
      - selenium-vscode
  ruby-2-4:
    <<: *app
  ruby-2-3:
    <<: *app
    build:
      <<: *app-build
      args:
        RUBY_VERSION: 2.3.4
  ruby-2-2:
    <<: *app
    build:
      <<: *app-build
      args:
        RUBY_VERSION: 2.2.7
  selenium-vscode:
    build:
      context: docker-selenium-vscode
    ports:
      - 5900
volumes:
  home:
  vendor:
